---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-join-controller
spec:
  selector:
    matchLabels: 
      name: vlan-join-controller
  template:
    metadata:
      labels:
        name: vlan-join-controller
    spec:
      nodeName: ""   
      containers:
      - image: stwalkerster/lke-vlan:main
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        name: vlan-join-controller
        env:
        - name: LINODE_API_TOKEN
          valueFrom:
           secretKeyRef:
            name: linode-api
            key: api_token
        - name: node_name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName 
        - name: vlan_name
          valueFrom:
            configMapKeyRef:
              name: vlan-join-controller-config
              key: vlan_name
        - name: vlan_cidr
          valueFrom:
            configMapKeyRef:
              name: vlan-join-controller-config
              key: vlan_cidr
      restartPolicy: Always